### ISSUE TITLE
Translation file not found

### ISSUE THREAD

**Issue by RonaldZav** [samerton/Nameless-Websend#3]
![image](https://user-images.githubusercontent.com/100430955/178151974-7a867dc3-35a0-44dd-96bd-89151a2102c6.png)
![image](https://user-images.githubusercontent.com/100430955/178151983-782a1bf3-bbd3-4dfd-bb61-b4be94a1baa7.png)

**Comment by samerton** [comment]
This module is not up to date with pre-release 13, and therefore cannot be used.

You can try this fork which might work with pre-release 13, but you will have to contact the author of the fork if there are any issues: https://github.com/supercrafter100/Nameless-Websend

**Comment by RonaldZav** [comment]
ok, thanks
